# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flylogger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.CharField(default='SOME STRING', max_length=100, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Full name'),
        ),
    ]
