# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flylogger', '0002_auto_20170504_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySurveillance',
            fields=[
                ('flarm_id', models.CharField(db_column='Flarm_ID', max_length=12, primary_key=True, serialize=False)),
                ('logged_date', models.DateField(db_column='Logged_Date')),
                ('note', models.CharField(blank=True, db_column='Note', max_length=150, null=True)),
            ],
            options={
                'db_table': 'Daily_Surveillance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FlightData',
            fields=[
                ('flight_no', models.AutoField(db_column='Flight_No', primary_key=True, serialize=False)),
                ('takeoff', models.TimeField(blank=True, db_column='Takeoff', null=True)),
                ('glider_landing', models.TimeField(blank=True, db_column='Glider_Landing', null=True)),
                ('max_height', models.IntegerField(blank=True, db_column='Max_Height', null=True)),
                ('logged_date', models.DateField(blank=True, db_column='Logged_Date', null=True)),
                ('flight_type', models.CharField(blank=True, db_column='Flight_Type', max_length=10, null=True)),
                ('towing_height', models.IntegerField(blank=True, db_column='Towing_Height', null=True)),
                ('towing_landing', models.TimeField(blank=True, db_column='Towing_Landing', null=True)),
                ('flight_status', models.CharField(blank=True, db_column='Flight_Status', max_length=20, null=True)),
                ('notes', models.CharField(blank=True, db_column='Notes', max_length=150, null=True)),
            ],
            options={
                'db_table': 'Flight_Data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Glider',
            fields=[
                ('glider_id', models.CharField(db_column='Glider_ID', max_length=12, unique=True)),
                ('flarm_id', models.CharField(db_column='Flarm_ID', max_length=12, primary_key=True, serialize=False)),
                ('daily_surveillance_performed', models.CharField(blank=True, db_column='Daily_Surveillance_Performed', max_length=150, null=True)),
            ],
            options={
                'db_table': 'Glider',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('pilot_id', models.IntegerField(db_column='Pilot_ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=150, null=True)),
            ],
            options={
                'db_table': 'Pilot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TowPlane',
            fields=[
                ('towing_id', models.CharField(db_column='Towing_ID', max_length=12, unique=True)),
                ('flarm_id', models.CharField(db_column='Flarm_ID', max_length=12, primary_key=True, serialize=False)),
                ('daily_surveillance_performed', models.CharField(blank=True, db_column='Daily_Surveillance_Performed', max_length=150, null=True)),
            ],
            options={
                'db_table': 'Tow_Plane',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Flew',
            fields=[
                ('flight_no', models.ForeignKey(db_column='Flight_No', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='flylogger.FlightData')),
                ('flight_type', models.CharField(db_column='Flight_Type', max_length=150)),
            ],
            options={
                'db_table': 'Flew',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Surveilled',
            fields=[
                ('flarm', models.ForeignKey(db_column='Flarm_ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='+', serialize=False, to='flylogger.DailySurveillance')),
            ],
            options={
                'db_table': 'Surveilled',
                'managed': False,
            },
        ),
    ]
